# Generated by Django 5.1.2 on 2024-10-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account_reference', models.CharField(default='isb-1234', max_length=200)),
                ('currency_code', models.CharField(default='EUR', max_length=10)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('currency', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.currencies')),
            ],
            options={
                'db_table': 'credit_transaction',
            },
        ),
        migrations.CreateModel(
            name='DebitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account_reference', models.CharField(default='isb-1234', max_length=200)),
                ('currency_code', models.CharField(default='EUR', max_length=10)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('currency', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.currencies')),
            ],
            options={
                'db_table': 'debit_transaction',
            },
        ),
    ]
