# Generated by Django 5.1.2 on 2024-10-13 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('TRANSFER', 'Transfer')], default='DEBIT', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_account_reference', models.CharField(max_length=200, null=True)),
                ('to_account_reference', models.CharField(max_length=200, null=True)),
                ('currency_reference', models.CharField(max_length=10, null=True)),
                ('currency', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.currencies')),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='accounts.account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='accounts.account')),
            ],
        ),
    ]
