# Generated by Django 5.1.2 on 2024-10-10 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_currencies_is_active_alter_account_currency_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittransaction',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='debittransaction',
            name='isbn',
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='account_reference',
            field=models.CharField(default='isb-1234', max_length=200),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='currency',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.currencies'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='debittransaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='debittransaction',
            name='account_reference',
            field=models.CharField(default='isb-1234', max_length=200),
        ),
        migrations.AddField(
            model_name='debittransaction',
            name='currency',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.currencies'),
        ),
        migrations.AddField(
            model_name='debittransaction',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=10),
        ),
    ]
