# Generated by Django 5.1.2 on 2024-10-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='pending', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('PREPAID', 'Prepaid')], default='DEBIT', max_length=10)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency_name', models.CharField(default='Euro', max_length=10, unique=True)),
                ('currency_code', models.CharField(default='EUR', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
