# Generated by Django 5.1.2 on 2024-10-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency_name', models.CharField(default='Euro', max_length=10)),
                ('currency_code', models.CharField(default='EUR', max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
