# Generated by Django 5.1.2 on 2024-10-10 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default='EUR', on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.currencies'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='currency_name',
            field=models.CharField(default='Euro', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('PREPAID', 'Prepaid')], default='DEBIT', max_length=10)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
