# Generated by Django 5.1.2 on 2024-10-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(default='Customers', max_length=100),
        ),
    ]
