# Generated by Django 5.1.2 on 2024-10-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_admin_id_remove_banker_id_remove_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
