# Generated by Django 5.1.2 on 2024-10-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
