# Generated by Django 5.1.2 on 2024-10-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(default='CUSTOMER', max_length=20),
        ),
    ]
