# Generated by Django 5.1.2 on 2024-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_name_remove_customuser_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('BANKER', 'Banker')], default='CUSTOMER', max_length=200),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
