# Generated by Django 5.1.2 on 2024-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_name_combination',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('BANKER', 'Banker'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
