# Generated by Django 5.1.2 on 2024-10-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('BANKER', 'Banker'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
