# Generated by Django 5.1.2 on 2024-10-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_currencies_is_active_alter_account_currency_and_more'),
        ('users', '0007_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Banker',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
