# Generated by Django 5.1.2 on 2024-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customer_user_delete_banker_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('BANKER', 'Banker'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=200),
        ),
    ]
