# Generated by Django 5.1.2 on 2024-10-09 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('PREPAID', 'Prepaid')], default='DEBIT', max_length=10)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
